/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nomadyt.aws.step.functions.activity.framework;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
